const cfg=window.GAME_API_CONFIG||{};
const loginScreen=document.getElementById('loginScreen');
const dashboard=document.getElementById('dashboard');
const pageContent=document.getElementById('pageContent');
const pageTitle=document.getElementById('pageTitle');
const adminEmail=document.getElementById('adminEmail');
const loginError=document.getElementById('loginError');
let supabaseClient=null;
function showError(message){loginError.textContent=message;loginError.hidden=false}
function configured(){return cfg.SUPABASE_URL&&cfg.SUPABASE_ANON_KEY&&!cfg.SUPABASE_URL.includes('PASTE_')&&!cfg.SUPABASE_ANON_KEY.includes('PASTE_')}
async function start(){if(!configured()){showError('Supabase authentication is not configured.');return}supabaseClient=window.supabase.createClient(cfg.SUPABASE_URL,cfg.SUPABASE_ANON_KEY);const {data}=await supabaseClient.auth.getSession();if(data.session)await authorize(data.session.user);else loginScreen.hidden=false;supabaseClient.auth.onAuthStateChange(async(event,session)=>{if(session)await authorize(session.user);else{dashboard.hidden=true;loginScreen.hidden=false}})}
async function authorize(user){const {data,error}=await supabaseClient.from('admin_users').select('user_id,role').eq('user_id',user.id).eq('role','admin').maybeSingle();if(error){console.error('Admin verification failed:',error);await supabaseClient.auth.signOut();showError('We could not verify administrator access. Please try again.');return}if(!data){await supabaseClient.auth.signOut();showError('Access denied. This account is not authorized for the administrator portal.');return}loginScreen.hidden=true;dashboard.hidden=false;adminEmail.textContent=user.email||'Administrator';render('overview')}
document.getElementById('loginForm').addEventListener('submit',async e=>{e.preventDefault();loginError.hidden=true;if(!supabaseClient){showError('Supabase authentication is not configured.');return}const email=document.getElementById('email').value.trim();const password=document.getElementById('password').value;const {error}=await supabaseClient.auth.signInWithPassword({email,password});if(error)showError('Sign in failed. Check your email and password.')});
document.getElementById('togglePassword').addEventListener('click',()=>{const input=document.getElementById('password');const btn=document.getElementById('togglePassword');const visible=input.type==='text';input.type=visible?'password':'text';btn.textContent=visible?'Show':'Hide';btn.setAttribute('aria-label',visible?'Show password':'Hide password')});
document.getElementById('logoutBtn').addEventListener('click',async()=>{if(supabaseClient)await supabaseClient.auth.signOut()});
document.querySelectorAll('.nav-item').forEach(btn=>btn.addEventListener('click',()=>{document.querySelectorAll('.nav-item').forEach(x=>x.classList.remove('active'));btn.classList.add('active');render(btn.dataset.page)}));
function render(page){const titles={overview:'Overview',users:'Users',games:'Games',api:'API & Keys',transactions:'Transactions',logs:'Activity Logs',settings:'Settings'};pageTitle.textContent=titles[page]||'Overview';const pages={overview:`<div class="grid"><div class="card"><div class="stat-label">TOTAL USERS</div><div class="stat-value">—</div><div class="stat-note">Customer accounts</div></div><div class="card"><div class="stat-label">ACTIVE GAMES</div><div class="stat-value">—</div><div class="stat-note">Crash & Big Odd rounds</div></div><div class="card"><div class="stat-label">API KEYS</div><div class="stat-value">—</div><div class="stat-note">Issued API credentials</div></div><div class="card"><div class="stat-label">SYSTEM</div><div class="stat-value">Online</div><div class="stat-note">Supabase connected</div></div></div><div class="section"><h3>Administration</h3><div class="empty">Administrator authentication is active. The remaining dashboard modules will be connected to your existing Supabase tables next.</div></div>`,users:`<div class="toolbar"><input placeholder="Search users..."></div><div class="empty">Customer management will load securely from Supabase.</div>`,games:`<div class="empty">Crash rounds and Big Odd rounds will appear here.</div>`,api:`<div class="empty">API keys and usage monitoring will appear here. Secret credentials will not be exposed in browser code.</div>`,transactions:`<div class="empty">Transaction management will appear here when the transaction data source is connected.</div>`,logs:`<div class="empty">Administrator activity logs will appear here.</div>`,settings:`<div class="card"><h3>Security</h3><p class="stat-note">Administrator membership is verified through Supabase Auth and the protected admin_users table. Privileged database operations should remain protected by Row Level Security or server-side Edge Functions.</p></div>`};pageContent.innerHTML=pages[page]||pages.overview}start();
